apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/operator-type: non-standalone
  name: recipe.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Recipe is the Schema for the recipes API
      displayName: Recipe
      kind: Recipe
      name: recipes.ramendr.openshift.io
      version: v1alpha1
  description: >
    Recipe describes a workflow used for capturing or recovering Kubernetes
    resources. This can be referred to by a Ramen DRPlacementControl object when
    kubeObjectProtection is enabled.
  displayName: Recipe
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
# installModes should match the installModes of the ODF operator as the
# recipe-crd-bundle is being installed as part of the ODF operator bundle.
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - recipe
  links:
  - name: Recipe
    url: https://github.com/ramendr/recipe
  maintainers:
  - email: bmekhiss@redhat.com
    name: Benamar Mekhissi
  - email: srangana@redhat.com
    name: Shyam Ranganathan
  maturity: alpha
  provider:
    name: Red Hat, Inc.
  version: 0.0.0
